source "https://supermarket.chef.io"

cookbook 'git', '~> 4.1.0'
cookbook 'kvm', '~> 0.3.1'
cookbook 'sqlite', '~> 1.1.0'
cookbook 'lxc', '~> 2.0.0'
cookbook 'golang', '~> 1.5.0'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'openssl', '~> 2.0.2'
cookbook 'zlib', '~> 2.0.0'
cookbook 'readline', '~> 0.0.5'
